### ISSUE TITLE
More templates

### ISSUE THREAD

**Issue by Limeisland** [TheMajesticSeagull/JSDF_Mission_Files#21]
Adding templates for more maps and stuff

### TEMPLATES TO BE ADDED:

- [x] Southern Sahrani
- [x] CLA Clafghan
- [x] Lingor
- [x] Dingor
- [x] Isla Abramia
- [x] Isla Duala

**Comment by JoramD** [comment]
You wanted the map `United Sahrani` correct? @Limeisland

**Comment by JoramD0** [comment]
### TEMPLATES TO BE ADDED:

- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by Limeisland** [comment]
@JoramD0 No its the Southern Sahrani map
