### ISSUE TITLE
UK army ranks

### ISSUE THREAD

**Issue by KennyBadrige** [TheMajesticSeagull/JSDF_Mission_Files#26]
Link to the mod- http://steamcommunity.com/sharedfiles/filedetails/?id=840620680&searchtext=british+rank

Screenshot of permission
![63afca366c68fd70635d766b5db4f171 1](https://user-images.githubusercontent.com/24608246/35836837-6510cbea-0ada-11e8-89c2-0b4e0b739b48.png)

screenshot in
![107410_screenshots_20180206014623_1 1](https://user-images.githubusercontent.com/24608246/35836863-85656db0-0ada-11e8-934d-b51ef3fc09bb.jpg)
game-

**Comment by JoramD** [comment]
Done, will be included in the next version of JSDF Resources
