### ISSUE TITLE
Auto Rank insignia system

### ISSUE THREAD

**Issue by budabuda** [TheMajesticSeagull/JSDF_Mission_Files#28]

**Comment by JoramD** [comment]
This is going to require a few things:
- [ ] Some kind of database
- [ ] A way to read the database
- [ ] A way for staff to easily edit that database (PHPmyAdmin?)
- [ ] Some way to set the insignia on the unit
- [ ] this needs to be bulletproof

**Comment by JoramD** [comment]
Not needed & too much work
